### ISSUE TITLE
[Feature Request] Run R128Gain with extensions.command_on_download.command

### ISSUE THREAD

**Issue by tordenflesk** [xthursdayx/docker-gpodder#9] opened 2021-05-31 17:35 UTC
Is there a way of adding R128Gain to my setup? https://github.com/desbma/r128gain
On my (Windows) desktop i have this value for extensions.command_on_download.command:
"C:\Users\Tordenflesk\scoop\shims\r128gain.exe" -a -s "%filename%" && echo done

## Describe the solution you'd like
A way of triggering external commands, like R128Gain.

## Alternatives you've considered
Current work-around is running it as a Windows scheduled task.

**Comment by tanja84dk** [comment] 2021-05-31 18:27
At first my thought is that it would be possible but personally I could be wrong.
At least I will try to look into the commands gpodder accepts and how it execute things when i get home because I cant see how it would defer from the way it already are able to integrate youtube-dl which also is a python project

EDIT:
Just got home and looking into it and reading gpodder source code.
For some reason I cant get it to recreate the thing you are saying you are doing ( nether on linux or windows ).
Wiuld it be posible to see a copy of your Settings.json ( the gPodder settings file ) to see if that gives me a clue why I cant recreate it?

Ofc remember to censor username and password like if you are using gpodder.net implementation before sharing it

**Comment by tanja84dk** [comment] 2021-06-01 00:14
I have looked into it and it actually pretty simple for you to add it yourself and I would be more then happy to guide you, but I dont feel it should be in the Docker image as default mainly because I didn't find a way to build it directly into gPodder except with the "extensions.command_on_download.command"

First of all how has you installed the Docker Container ( is it on a nas, server etc and what operating system? )

**Comment by tordenflesk** [comment] 2021-06-01 00:20
I've added it using a stack in portainer:
```---
version: "2.1"
services:
  gPodder:
    image: xthursdayx/gpodder-docker
    container_name: gPodder
    environment:
      - TZ=Europe/Oslo
      - HEIGHT=720
      - WIDTH=1280
      - GUAC_USER=Tordenflesk
      - GUAC_PASS=TotallySecretPassword
    volumes:
      - /srv/dev-disk-by-label-DATA01/Docker_Config/GPODDER:/config
      - /srv/dev-disk-by-label-DATA00/media/podcasts:/downloads
    ports:
      - 3388:8080
      - 3389:3389
    restart: unless-stopped
```

Debian 10 x64, OpenMediaVault 5

**Comment by tanja84dk** [comment] 2021-06-01 00:33
Do you have access to a terminal command prompt?

**Comment by tanja84dk** [comment] 2021-06-01 00:48
With in a terminal ( command line ):
run following:
```
docker exec -it gPodder bash
```

It spawns a bash shell within the docker container so you have access to the containers filesystem

when you are entered into the container ( it will probebly say root@"some-hostname" ) then run the following to install the python version of the program.

```
pip3 install r128gain
```

then go into the gPodder gui as normal and activate the extensions.command_on_download.command and the following in the command you need to add just as in windows.
/usr/local/bin/ in the path pip3 should be installing r128gain into
Notice there is  only one $ infront of filename and none after, also "" around just in case there is space in some files filename or folder path.

What I could find out from looking at other functions within the gPodder program and source it looked like $filename is the official variable it uses in the end for the filename ( posible even file path ), and tested it on a dev container here at home and it looked like it worked

```
/usr/local/bin/r128gain -a -s "$filename" && echo done
```

**Comment by tordenflesk** [comment] 2021-06-01 01:46
`/usr/local/bin/r128gain -a -s "$filename" && echo done` didn't work, but `/usr/local/bin/r128gain -a -r -s /downloads && echo done` did. That's the same command I now run as a cron task on the host. My guess is that there's an issue with "$filename". I've tried both single & double quotes.

Also, wouldn't R128Gain disappear whenever the container gets updated?

**Comment by tordenflesk** [comment] 2021-06-01 01:51
Doing a test-run inside the container I also get this error:
root@89a61a2d7180:/# r128gain -a -r /downloads/
Analyzing loudness of file '/downloads/Berrum & Beyer snakker om greier/2021-06-01 - Gjen\udcc3\udca5pning, Influencerspons og Strandpappa.mp3'...
Analyzing loudness of file '/downloads/Rekommandert/2021-06-01 - Freakshows.mp3'...
Analyzing loudness of file '/downloads/Rekommandert/2021-06-01 - Freakshows.mp3'...
Analyzing loudness of file '/downloads/Berrum & Beyer snakker om greier/2021-06-01 - Gjen\udcc3\udca5pning, Influencerspons og Strandpappa.mp3'...
**Failed to analyze file '/downloads/Berrum & Beyer snakker om greier/2021-06-01 - Gjen\udcc3\udca5pning, Influencerspons og Strandpappa.mp3': UnicodeEncodeError 'utf-8' codec can't encode characters in position 91-92: surrogates not allowed
Failed to analyze files '/downloads/Berrum & Beyer snakker om greier/2021-06-01 - Gjen\udcc3\udca5pning, Influencerspons og Strandpappa.mp3': UnicodeEncodeError 'utf-8' codec can't encode characters in position 91-92: surrogates not allowed**
File '/downloads/Berrum & Beyer snakker om greier/2021-06-01 - Gjen\udcc3\udca5pning, Influencerspons og Strandpappa.mp3': loudness = SKIPPED, sample peak = SKIPPED
Album '/downloads/Berrum & Beyer snakker om greier': loudness = SKIPPED, sample peak = SKIPPED
File '/downloads/Rekommandert/2021-06-01 - Freakshows.mp3': loudness = -22.5 LUFS, sample peak = -0.5 dBFS
Album '/downloads/Rekommandert': loudness = -22.5 LUFS, sample peak = -0.5 dBFS
Tagging file '/downloads/Rekommandert/2021-06-01 - Freakshows.mp3'

Those paths don't look right to me.

**Comment by tanja84dk** [comment] 2021-06-01 02:14
I'm sorry for the late response
Its weird that you say that the $filename doesn't work guess there is something in your Settings.json there is changed from default.
The reason you think its working without the "$filename" is because you are then not escaping or looking for variables so you are actually ignoring them, witch is never a good idea.

And one of the mayjor issues its reading spaces as several commands in many cases witch is why " are used because that tells the program see all this input as one long filename

Would it be possible to see your Settings.json there should be located in this folder on your system based on your stack configuration and remember to sanitize password if you are using gpodder.net 
```
/srv/dev-disk-by-label-DATA01/Docker_Config/GPODDER/gPodder/
```
It is to try to spot what the issue is and also to test in my test container with your configuration.

**Comment by tanja84dk** [comment] 2021-06-01 02:59
also I noticed it errors about UTF-8 ( witch I have seen before myself )

Just to make sure, if you go into Portainer under images what date does it then say that the xthursdayx/gpodder-docker is created

EDIT:
And just to update, I have just tested two podcasts you showed in your log and those worked fine, also with the guide I sent you, so I believe something is up in your settings file or you got something miss typed and that was with the "$filetype".

Just to show you from the output ( btw its renaming the files after the command is done because that is how gPodder does it)

```
File '/downloads/Berrum & Beyer snakker om greier/69678b6b-7bba-47f4-a4e7-371700261be8_4e4da690b11362d79230f8ba33c078d2.mp3': loudness = -21.7 LUFS, sample peak = 0.0 dBFS
Album '/downloads/Berrum & Beyer snakker om greier': loudness = -21.7 LUFS, sample peak = 0.0 dBFS
Tagging file '/downloads/Berrum & Beyer snakker om greier/69678b6b-7bba-47f4-a4e7-371700261be8_4e4da690b11362d79230f8ba33c078d2.mp3'
done
File '/downloads/Rekommandert/b3bdac6d-453c-40d9-a417-5a6131c8588e_3dbd609e14fb4e64187789b5b42a82cc.mp3': loudness = -20.2 LUFS, sample peak = -0.6 dBFS
Album '/downloads/Rekommandert': loudness = -20.2 LUFS, sample peak = -0.6 dBFS
Tagging file '/downloads/Rekommandert/b3bdac6d-453c-40d9-a417-5a6131c8588e_3dbd609e14fb4e64187789b5b42a82cc.mp3'
done
File '/downloads/Rekommandert/cd9a2d56-2c01-4156-8ded-83b27468dea2_789d925dcf6a8a894272e5b61bbd2497.mp3': loudness = -22.6 LUFS, sample peak = -0.4 dBFS
Album '/downloads/Rekommandert': loudness = -22.6 LUFS, sample peak = -0.4 dBFS
Tagging file '/downloads/Rekommandert/cd9a2d56-2c01-4156-8ded-83b27468dea2_789d925dcf6a8a894272e5b61bbd2497.mp3'
done
```

**Comment by tordenflesk** [comment] 2021-06-01 11:17
> also I noticed it errors about UTF-8 ( witch I have seen before myself )
> 
> Just to make sure, if you go into Portainer under images what date does it then say that the xthursdayx/gpodder-docker is created

2021-04-12 18:31:58
```
{
  "auto": {
    "cleanup": {
      "days": 7,
      "played": false,
      "unfinished": false,
      "unplayed": false
    },
    "retries": 3,
    "update": {
      "enabled": true,
      "frequency": 10
    }
  },
  "device_sync": {
    "after_sync": {
      "delete_episodes": false,
      "mark_episodes_played": false,
      "sync_disks": false
    },
    "custom_sync_name": "{episode.sortdate}_{episode.title}",
    "custom_sync_name_enabled": false,
    "delete_played_episodes": false,
    "device_folder": "/media",
    "device_type": "none",
    "max_filename_length": 120,
    "one_folder_per_podcast": true,
    "playlists": {
      "create": true,
      "folder": "Playlists",
      "two_way_sync": false,
      "use_absolute_path": true
    },
    "skip_played_episodes": true
  },
  "downloads": {
    "chronological_order": true
  },
  "extensions": {
    "command_on_download": {
      "command": "/usr/local/bin/r128gain -a -s \"$filename\" && echo done"
    },
    "enabled": [
      "update_feeds_on_startup",
      "rename_download",
      "tagging",
      "filter"
    ],
    "filter": {
      "filters": [
        {
          "block": "destillert",
          "block_ic": true,
          "url": "https://smartpod.no/feed/misjonen"
        }
      ]
    },
    "rename_download": {
      "add_podcast_title": false,
      "add_sortdate": true
    },
    "tagging": {
      "always_remove_tags": false,
      "auto_embed_coverart": true,
      "genre_tag": "Podcast",
      "modify_tags": true,
      "set_artist_to_album": true,
      "set_version": 4,
      "strip_album_from_title": true
    }
  },
  "limit": {
    "bandwidth": {
      "enabled": false,
      "kbps": 500.0
    },
    "downloads": {
      "concurrent": 1,
      "concurrent_max": 16,
      "enabled": true
    },
    "episodes": 200
  },
  "mygpo": {
    "device": {
      "caption": "gPodder on 2da729c230fb",
      "type": "desktop",
      "uid": "2da729c230fb"
    },
    "enabled": false,
    "password": "",
    "server": "gpodder.net",
    "username": ""
  },
  "player": {
    "audio": "default",
    "video": "default"
  },
  "software_update": {
    "check_on_startup": true,
    "interval": 5,
    "last_check": 1622478429
  },
  "ui": {
    "cli": {
      "colors": true
    },
    "gtk": {
      "download_list": {
        "remove_finished": true
      },
      "episode_list": {
        "columns": 6,
        "descriptions": true,
        "view_mode": 0
      },
      "html_shownotes": true,
      "live_search_delay": 200,
      "new_episodes": "show",
      "podcast_list": {
        "all_episodes": true,
        "hide_empty": false,
        "sections": true,
        "view_mode": 1
      },
      "search_always_visible": false,
      "state": {
        "config_editor": {
          "height": 729,
          "maximized": false,
          "width": 1535,
          "x": 49,
          "y": 187
        },
        "episode_selector": {
          "height": 400,
          "maximized": false,
          "width": 600,
          "x": -1,
          "y": -1
        },
        "episode_window": {
          "height": 400,
          "maximized": false,
          "width": 500,
          "x": -1,
          "y": -1
        },
        "export_to_local_folder": {
          "height": 400,
          "maximized": false,
          "width": 500,
          "x": -1,
          "y": -1
        },
        "main_window": {
          "episode_column_order": [],
          "episode_column_sort_id": 12,
          "episode_column_sort_order": false,
          "episode_list_size": 200,
          "height": 500,
          "maximized": false,
          "paned_position": 200,
          "width": 700,
          "x": -1,
          "y": -1
        },
        "preferences": {
          "height": -1,
          "maximized": false,
          "width": -1,
          "x": -1,
          "y": -1
        }
      },
      "toolbar": false
    }
  },
  "vimeo": {
    "fileformat": "1080p"
  },
  "youtube": {
    "preferred_fmt_id": 37,
    "preferred_fmt_ids": [],
    "preferred_hls_fmt_id": 96,
    "preferred_hls_fmt_ids": []
  }
}
```

**Comment by xthursdayx** [comment] 2021-06-02 03:27
As @tanja84dk suggests, I don't think that the best approach will be to build this into the docker image itself since it doesn't seem to directly relate to gPodder's core functionality. 

The UTF errors you're seeing have to do with the way that gPodder (as a Python3 app) is decoding filenames into and out of Unicode.  The normal UTF8 encoder can't handle these "partial surrogates" when printing to the terminal, but it should affect usage within gPodder. 

I will close this issue for now, but you can continue to discuss and troubleshoot R128Gain into your system, and if you think it is warranted at some point in the future I can reopen the issue.

**Closed as completed by xthursdayx** 2021-06-02 03:27 UTC

**Comment by tanja84dk** [comment] 2021-06-02 14:11
I'm sorry forgot to update yesterday, got way to much work and study so was over stressed

I have done some testing including testing his setting file today, And I believe the UTF-8 error was because he chose to remove the quoted filename variable witch made it break, because it then treats the folder as a file witch messing it up.

@tordenflesk remember the custom execute command is only for new files because it does only treat files there just are downloaded. And again the "" around $filename is necessary because if there for some reason is spaces in a filename while downloading
Also my test with your configuration went fine and I had no issues with it.
Log Output from a new clean container again configured with the guide I wrote earlier 

```
Analyzing loudness of file '/downloads/Berrum & Beyer snakker om greier/media-ko8te8kn-b-b_030521.mp3'...
Analyzing loudness of file '/downloads/Berrum & Beyer snakker om greier/media-ko8te8kn-b-b_030521.mp3'...
File '/downloads/Berrum & Beyer snakker om greier/media-ko8te8kn-b-b_030521.mp3': loudness = -18.4 LUFS, sample peak = -0.4 dBFS
Album '/downloads/Berrum & Beyer snakker om greier': loudness = -18.4 LUFS, sample peak = -0.4 dBFS
Tagging file '/downloads/Berrum & Beyer snakker om greier/media-ko8te8kn-b-b_030521.mp3'
done
Analyzing loudness of file '/downloads/Berrum & Beyer snakker om greier/media-kojs0dmh-berrum-beyer_10-05-21_bruk.mp3'...
Analyzing loudness of file '/downloads/Berrum & Beyer snakker om greier/media-kojs0dmh-berrum-beyer_10-05-21_bruk.mp3'...
Analyzing audio loudness:   0% 0/2 [00:00<?, ? files/s]rdpSaveScreen:
File '/downloads/Berrum & Beyer snakker om greier/media-kojs0dmh-berrum-beyer_10-05-21_bruk.mp3': loudness = -16.9 LUFS, sample peak = -0.2 dBFS
Album '/downloads/Berrum & Beyer snakker om greier': loudness = -16.9 LUFS, sample peak = -0.2 dBFS
Tagging file '/downloads/Berrum & Beyer snakker om greier/media-kojs0dmh-berrum-beyer_10-05-21_bruk.mp3'
done
```

And when I looked in the folder the files were renamed as they should be so it worked as intended

**Comment by xthursdayx** [comment] 2021-06-03 17:53
Just FYI, you'll both likely want to repull my gPodder docker image as I've just made a major update, which (I hope) addresses some of the lingering annoying (but ultimately unimportant) errors messages and reduces the image size. Cheers!

**Comment by tanja84dk** [comment] 2021-06-04 13:38
Thanks for the update but tbh I'm gonna stay on my own version ( To make sure my workflow doesn't break ), but to be fair to you I'm not going to share my version to not compete with you ( And also not sure about license rules etc )

But I do really appreciate your work witch is why I'm still trying to help in here
